travis:
  secure:
    BINSTAR_TOKEN: Xh42FO8JEVV55LngKqvTHf1/ImKMbKjiseT5jTkwfH3RONIQKM/ZRB6CEw36Bt9suepw6K+XvzSPpbJjdLZjt2UmfJl1yJI4C+PSOUae8GtOnNTxxQSZ2PL/XFV6xCSMKi4cQIWkzS45YTfpjUGsRPkT5j41io0f4zvQaotTm6n6QXYfsKws+SjQ0KE8Xz6dQwMNB3Uzq2gQ1UofdVGYEkXahy/60cu5We+VOsb+eujnkeB0YBxlp+HPeO+Yczp8tFlZCrTDGaUlBluf4dEH7Fq1gxWJ+Hq0hXk2WALR/MK+EllOZEIql69bussXb/9i0ZcZiJBOyvM9FjmCktWeK8RtSEXkHbKvmMwETkyQ+8ieXETILMW5DLuJKFUngePbt3WlQug4D4bV9qi2Tp7ssLDQW0IZLQsFCoStENq5s3huamSzbchYUWgvf/ss6gqSxRKkdfeb/Kgpx+2fEWCZt1WwvXK4i9XVr90K0BPlsxVBeM3iPb6UsTNemRoh2duh0wP7QdLEOvJica4aVBh4BXHgAdm5b5vvoEjaNMpghPCITEbIQulpVR0M5OkwVBZq5Pm6CvrgmCih0/tlhgL6CPYelcDKDPAB2KqOCqKZ4NPkguVIVRZuFkZcYgvJwswPB4/OnAyMXdHr0HvptnDR3a9RAkiTls0qPN28vd1L84I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
