travis:
  secure:
    BINSTAR_TOKEN: HbcDsEHBOHTy2Bpu7ni0tv1/doCbw1aTKmqXBCIIs2xyD6iZRQaxIWjs3kCAVT3SGGEOjzu2RiaaSz1258v6piYlDVvu22z7U/VCRJ++i6cLmOyjuB+HuQWkszMANnX+u6W9Jr25P+kklkvI4phhZK64yIrUxgQeAjsHw9ZFmnOAlJjU/iI3FmmX9JuTg3yVbsR9BXmiGCqfRYqM/zm2avxE4onEVZIYM9e7qy4YdwHqDpeuyH2bLw/Ik5Wg0d7Yzwd6PIAkL0aC1BIxMjF5JdXbonGqWUfdd/bs2o+Etv7rdj77NkzUx3aK8jq4BOMOO64Ts7rNvKH8/nJ1PQMBsU17MAA8oE5geDOr1boNrGQucyKoHrRNjvRB+XK9xhncy5YJ6MLTzmLd5835CrBsZxct1uYDVXZ05y0ckQTl0Zs/cIQ0cOqO9haaHCLBU8SmjlyxpYiVL7xNepW2OSt9Rke9GcnSDdiWjudn86vxrZuyAIloP99dZxBINrjanLMvaugJyQVKm4WKiHaRJ/rwntKsFFrKO1lRTC5x481qPQmFzApdty5BzDUj88bUzs9VxN958DJeetJrTK+dPIcrqtZfKiXxlIeeg4s2RdRtCEDssGPG2BXX4NXxGYRz9Qr5yDhCwEjpCPoxFXBTLZKldWgbQNhsxICnrgz3ze+7zqo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
